// <auto-generated />
using System;
using HotelParadiseResort.Persistence.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelParadiseResort.Persistence.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260727220529_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("IX_Cliente_Identificacion");

                    b.HasIndex("Apellidos", "Nombre")
                        .HasDatabaseName("IX_Cliente_Apellidos_Nombre");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Consumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<int>("EstadiaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaConsumo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServicioAdicionalId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("EstadiaId")
                        .HasDatabaseName("IX_Consumo_Estadia");

                    b.HasIndex("FechaConsumo")
                        .HasDatabaseName("IX_Consumo_Fecha");

                    b.HasIndex("ServicioAdicionalId");

                    b.HasIndex("UsuarioRegistroId");

                    b.ToTable("Consumo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Consumo_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_Consumo_PrecioUnitario", "[PrecioUnitario] >= 0");
                        });
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("EsHospedaje")
                        .HasColumnType("bit");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaConsumo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId")
                        .HasDatabaseName("IX_DetalleFactura_Factura");

                    b.ToTable("DetalleFactura", (string)null);
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Estadia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadHuespedes")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCheckInId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCheckOutId")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("FechaCheckIn")
                        .HasDatabaseName("IX_Estadia_FechaCheckIn");

                    b.HasIndex("ReservaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Estadia_Reserva");

                    b.HasIndex("UsuarioCheckInId");

                    b.HasIndex("UsuarioCheckOutId");

                    b.HasIndex("HabitacionId", "Estado")
                        .HasDatabaseName("IX_Estadia_Habitacion_Estado");

                    b.ToTable("Estadia", null, t =>
                        {
                            t.HasCheckConstraint("CK_Estadia_FechaCheckOut", "[FechaCheckOut] IS NULL OR [FechaCheckOut] >= [FechaCheckIn]");

                            t.HasCheckConstraint("CK_Estadia_Huespedes", "[CantidadHuespedes] > 0");
                        });
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstadiaId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("int");

                    b.Property<string>("EstrategiaTarifa")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("JustificacionDescuento")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<int>("Noches")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<decimal>("SubtotalConsumos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubtotalHospedaje")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifaPorNoche")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioEmisionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadiaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Factura_Estadia");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_Factura_Numero");

                    b.HasIndex("UsuarioEmisionId");

                    b.HasIndex("FechaEmision", "EstadoPago")
                        .HasDatabaseName("IX_Factura_FechaEmision_EstadoPago");

                    b.ToTable("Factura", null, t =>
                        {
                            t.HasCheckConstraint("CK_Factura_Descuento", "[Descuento] <= [SubtotalHospedaje] + [SubtotalConsumos]");

                            t.HasCheckConstraint("CK_Factura_Montos", "[SubtotalHospedaje] >= 0 AND [SubtotalConsumos] >= 0 AND [Descuento] >= 0 AND [Total] >= 0");
                        });
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.Property<int>("TipoHabitacionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_Habitacion_Numero");

                    b.HasIndex("TipoHabitacionId");

                    b.HasIndex("Estado", "TipoHabitacionId")
                        .HasDatabaseName("IX_Habitacion_Estado_Tipo");

                    b.ToTable("Habitacion", (string)null);
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.HistorialCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ClienteId", "FechaRegistro")
                        .HasDatabaseName("IX_HistorialCliente_Cliente_Fecha");

                    b.ToTable("HistorialCliente", (string)null);
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanalOrigen")
                        .HasColumnType("int");

                    b.Property<int>("CantidadHuespedes")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("date");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Reserva_Cliente");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Reserva_Codigo");

                    b.HasIndex("UsuarioRegistroId");

                    b.HasIndex("Estado", "FechaEntrada")
                        .HasDatabaseName("IX_Reserva_Estado_FechaEntrada");

                    b.HasIndex("HabitacionId", "FechaEntrada", "FechaSalida", "Estado")
                        .HasDatabaseName("IX_Reserva_Habitacion_Fechas_Estado");

                    b.ToTable("Reserva", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reserva_Fechas", "[FechaSalida] >= [FechaEntrada]");

                            t.HasCheckConstraint("CK_Reserva_Huespedes", "[CantidadHuespedes] > 0");

                            t.HasCheckConstraint("CK_Reserva_Monto", "[MontoEstimado] >= 0");
                        });
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.ServicioAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_ServicioAdicional_Nombre");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IX_ServicioAdicional_Tipo");

                    b.ToTable("ServicioAdicional", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServicioAdicional_Precio", "[PrecioBase] >= 0");
                        });
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.TipoHabitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<decimal>("TarifaBasePorNoche")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_TipoHabitacion_Nombre");

                    b.ToTable("TipoHabitacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_TipoHabitacion_Capacidad", "[CapacidadMaxima] > 0");

                            t.HasCheckConstraint("CK_TipoHabitacion_Tarifa", "[TarifaBasePorNoche] >= 0");
                        });
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuario_Correo");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuario_NombreUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Consumo", b =>
                {
                    b.HasOne("HotelParadiseResort.Domain.Entidades.Estadia", "Estadia")
                        .WithMany("Consumos")
                        .HasForeignKey("EstadiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelParadiseResort.Domain.Entidades.ServicioAdicional", "ServicioAdicional")
                        .WithMany("Consumos")
                        .HasForeignKey("ServicioAdicionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelParadiseResort.Domain.Entidades.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estadia");

                    b.Navigation("ServicioAdicional");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.DetalleFactura", b =>
                {
                    b.HasOne("HotelParadiseResort.Domain.Entidades.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Estadia", b =>
                {
                    b.HasOne("HotelParadiseResort.Domain.Entidades.Habitacion", "Habitacion")
                        .WithMany("Estadias")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelParadiseResort.Domain.Entidades.Reserva", "Reserva")
                        .WithOne("Estadia")
                        .HasForeignKey("HotelParadiseResort.Domain.Entidades.Estadia", "ReservaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelParadiseResort.Domain.Entidades.Usuario", "UsuarioCheckIn")
                        .WithMany()
                        .HasForeignKey("UsuarioCheckInId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelParadiseResort.Domain.Entidades.Usuario", "UsuarioCheckOut")
                        .WithMany()
                        .HasForeignKey("UsuarioCheckOutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Habitacion");

                    b.Navigation("Reserva");

                    b.Navigation("UsuarioCheckIn");

                    b.Navigation("UsuarioCheckOut");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Factura", b =>
                {
                    b.HasOne("HotelParadiseResort.Domain.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelParadiseResort.Domain.Entidades.Estadia", "Estadia")
                        .WithOne("Factura")
                        .HasForeignKey("HotelParadiseResort.Domain.Entidades.Factura", "EstadiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelParadiseResort.Domain.Entidades.Usuario", "UsuarioEmision")
                        .WithMany()
                        .HasForeignKey("UsuarioEmisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estadia");

                    b.Navigation("UsuarioEmision");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Habitacion", b =>
                {
                    b.HasOne("HotelParadiseResort.Domain.Entidades.TipoHabitacion", "TipoHabitacion")
                        .WithMany("Habitaciones")
                        .HasForeignKey("TipoHabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoHabitacion");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.HistorialCliente", b =>
                {
                    b.HasOne("HotelParadiseResort.Domain.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelParadiseResort.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Reserva", b =>
                {
                    b.HasOne("HotelParadiseResort.Domain.Entidades.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelParadiseResort.Domain.Entidades.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelParadiseResort.Domain.Entidades.Usuario", "UsuarioRegistro")
                        .WithMany("ReservasGestionadas")
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Habitacion");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Estadia", b =>
                {
                    b.Navigation("Consumos");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Habitacion", b =>
                {
                    b.Navigation("Estadias");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Reserva", b =>
                {
                    b.Navigation("Estadia");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.ServicioAdicional", b =>
                {
                    b.Navigation("Consumos");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.TipoHabitacion", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("HotelParadiseResort.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("ReservasGestionadas");
                });
#pragma warning restore 612, 618
        }
    }
}
